version: '3'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
    - php
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/etc/nginx/logs
      - ./www:/data/www
    networks:
      - net-php
  php:
    build: ./php
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/conf.d:/usr/local/etc/php/conf.d
      - ./php/logs:/usr/local/var/log
      - ./www:/data/www
    networks:
      - net-php
networks:
  net-php:
